# Generated by Django 6.0.3 on 2026-03-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('zh', '中文'), ('en', 'English')], db_index=True, default='zh', max_length=2)),
                ('summary', models.CharField(help_text='Event title/name', max_length=500)),
                ('date_start', models.DateField(db_index=True, help_text='Event start date')),
                ('date_end', models.DateField(blank=True, help_text='Event end date', null=True)),
                ('location', models.CharField(blank=True, default='', help_text='Event location', max_length=500)),
                ('description', models.TextField(blank=True, default='', help_text='Event description')),
                ('uid', models.CharField(db_index=True, help_text='Unique identifier from ICS', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Calendar Event',
                'verbose_name_plural': 'Calendar Events',
                'ordering': ['date_start'],
                'indexes': [models.Index(fields=['language', 'date_start'], name='events_cale_languag_252225_idx'), models.Index(fields=['date_start', 'date_end'], name='events_cale_date_st_9705e9_idx')],
            },
        ),
    ]
