# Generated by Django 6.0.3 on 2026-03-28 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_announcement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.RenameIndex(
            model_name='announcement',
            new_name='events_anno_languag_78f94a_idx',
            old_name='events_anno_languag_d5eb96_idx',
        ),
        migrations.RenameIndex(
            model_name='announcement',
            new_name='events_anno_languag_f6e6f3_idx',
            old_name='events_anno_languag_9caad8_idx',
        ),
    ]
