# Generated by Django 6.0.3 on 2026-03-31 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_userpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('icon', models.CharField(max_length=10)),
                ('label', models.CharField(max_length=100)),
                ('label_en', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LinkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('label_en', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.URLField(max_length=500)),
                ('icon', models.URLField(max_length=500)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='events.linkcategory')),
            ],
        ),
    ]
