# Generated by Django 6.0.3 on 2026-04-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_feedbackpost_avatar_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkitem',
            name='embedding',
        ),
        migrations.AddField(
            model_name='linkitem',
            name='embeddings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='linkitem',
            name='keywords',
            field=models.TextField(blank=True),
        ),
    ]
