# Generated by Django 6.0.3 on 2026-04-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkitem',
            name='url_en',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
