# Generated by Django 6.0.3 on 2026-04-11 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_contactmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedbackpost",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="events.feedbackpost",
            ),
        ),
    ]
