# Generated by Django 6.0.3 on 2026-04-11 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_feedbackpost_parent"),
        ("events", "0010_linkitem_url_en"),
    ]

    operations = []
