// src/services/embed.ts
// Handles query encoding at search time.
// Document embeddings are generated by scripts/fetch_myntu_links.ts at import time.
//
// IMPORTANT: Both this file and the import script must use the same model.
// Current model : nvidia/llama-nemotron-embed-vl-1b-v2:free (2048 dims)

const OPENROUTER_API_KEY = process.env.OPENROUTER_API_KEY ?? "";
const EMBED_MODEL = "nvidia/llama-nemotron-embed-vl-1b-v2:free";

/**
 * Encodes a user search query into a 2048-dim vector via OpenRouter.
 * Uses input_type="query" — the bi-encoder distinction matters for retrieval quality.
 */
export async function encodeQuery(text: string): Promise<number[]> {
  if (!OPENROUTER_API_KEY) {
    throw new Error("Missing OPENROUTER_API_KEY environment variable");
  }

  const res = await fetch("https://openrouter.ai/api/v1/embeddings", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${OPENROUTER_API_KEY}`,
      "HTTP-Referer": "https://my.ntu.edu.tw",
    },
    body: JSON.stringify({
      model: EMBED_MODEL,
      input: [text],
      input_type: "query",   // ← query, not passage
      modality: ["text"],
    }),
  });

  if (!res.ok) {
    const body = await res.text();
    throw new Error(`OpenRouter embed failed [${res.status}]: ${body}`);
  }

  const json = (await res.json()) as {
    data: Array<{ index: number; embedding: number[] }>;
  };

  return json.data[0]!.embedding;
}

/** Cosine similarity between two equal-length vectors */
export function cosineSim(a: number[], b: number[]): number {
  let dot = 0, normA = 0, normB = 0;
  for (let i = 0; i < a.length; i++) {
    dot   += a[i]! * b[i]!;
    normA += a[i]! * a[i]!;
    normB += b[i]! * b[i]!;
  }
  return dot / (Math.sqrt(normA) * Math.sqrt(normB));
}

/** MaxSim: highest similarity among all vectors stored for an item */
export function maxSim(query: number[], vecs: number[][]): number {
  if (!vecs.length) return 0;
  return Math.max(...vecs.map((v) => cosineSim(query, v)));
}